version: '2'

services:
  hoptocopter:
    volumes:
        - .:/go/src/app
    working_dir: /go/src/app
    build: .
    ports:
     - "8080:8080"
    restart: always
  shields:
    image: "beevelop/shields"
    restart: always
